version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=dpg-cp4drd0cmk4c73einfv0-a
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=test
      - DATABASE_PASSWORD=iASK5B0KirkNoh4wZ5seDolvZjEwya8O
      - DATABASE_NAME=test_n6um
      - JWT_SECRET=topSecret51
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  db:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: iASK5B0KirkNoh4wZ5seDolvZjEwya8O
      POSTGRES_DB: test_n6um
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
